/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu_interface;

import menu_management.MainMenuController;

/**
 *
 * @author BERKYILDIZ
 */
public class NumberOfPlayerView extends javax.swing.JPanel {
    
    MainMenuController menuManager;

    /**
     * Creates new form NumberOfPlayerView
     */
    public NumberOfPlayerView(MainMenuController menuManager) {
        this.menuManager = menuManager;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        multiPlayerButton = new javax.swing.JButton();
        singlePlayerButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(null);

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 0, 0));
        backButton.setText("BACK");
        backButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(11, 11, 100, 50);

        multiPlayerButton.setBackground(new java.awt.Color(255, 255, 255));
        multiPlayerButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        multiPlayerButton.setForeground(new java.awt.Color(0, 0, 0));
        multiPlayerButton.setText("Multiplayer");
        multiPlayerButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        multiPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiPlayerButtonActionPerformed(evt);
            }
        });
        add(multiPlayerButton);
        multiPlayerButton.setBounds(300, 376, 200, 100);

        singlePlayerButton.setBackground(new java.awt.Color(255, 255, 255));
        singlePlayerButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        singlePlayerButton.setForeground(new java.awt.Color(0, 0, 0));
        singlePlayerButton.setText("Single Player");
        singlePlayerButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        singlePlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singlePlayerButtonActionPerformed(evt);
            }
        });
        add(singlePlayerButton);
        singlePlayerButton.setBounds(300, 220, 200, 100);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Select Player");
        add(jLabel4);
        jLabel4.setBounds(280, 80, 240, 70);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/sera/Desktop/outside.jpeg")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 3, true));
        jLabel2.setSize(new java.awt.Dimension(430, 110));
        add(jLabel2);
        jLabel2.setBounds(190, 60, 430, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/sera/Desktop/backGround.png")); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        menuManager.setNumberOfPlayers(0);
        menuManager.showView("mainmenu");
    }//GEN-LAST:event_backButtonActionPerformed

    private void singlePlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singlePlayerButtonActionPerformed
        menuManager.setNumberOfPlayers(1);
        menuManager.showView("gamemode");
    }//GEN-LAST:event_singlePlayerButtonActionPerformed

    private void multiPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiPlayerButtonActionPerformed
        menuManager.setNumberOfPlayers(2);
    }//GEN-LAST:event_multiPlayerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton multiPlayerButton;
    private javax.swing.JButton singlePlayerButton;
    // End of variables declaration//GEN-END:variables
}
