/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu_interface;

import menu_management.MainMenuController;

/**
 *
 * @author BERKYILDIZ
 */
public class GameModeScreen extends javax.swing.JPanel {
    MainMenuController menuController;
    /**
     * Creates new form GameModeScreen
     */
    public GameModeScreen(MainMenuController menuController) {
        this.menuController = menuController;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        classicButton = new javax.swing.JButton();
        arcadeButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(null);

        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(11, 11, 100, 50);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("                      GAME MODES");
        add(jLabel1);
        jLabel1.setBounds(190, 100, 340, 50);

        classicButton.setText("Classic");
        classicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classicButtonActionPerformed(evt);
            }
        });
        add(classicButton);
        classicButton.setBounds(300, 210, 200, 100);

        arcadeButton.setText("Arcade");
        arcadeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arcadeButtonActionPerformed(evt);
            }
        });
        add(arcadeButton);
        arcadeButton.setBounds(300, 376, 200, 100);
    }// </editor-fold>//GEN-END:initComponents

    private void classicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classicButtonActionPerformed
        menuController.setGameMode("classic");
        menuController.showView("level");
    }//GEN-LAST:event_classicButtonActionPerformed

    private void arcadeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arcadeButtonActionPerformed
        menuController.setGameMode("arcade");

    }//GEN-LAST:event_arcadeButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        menuController.setGameMode("");
        menuController.showView("numberofplayer");
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arcadeButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton classicButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
