/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu_interface;

/**
 *
 * @author BERKYILDIZ
 */
public class LeaderboardView extends javax.swing.JFrame {

    /**
     * Creates new form LeaderboardView
     */
    public LeaderboardView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        getContentPane().setLayout(null);

        jLabel1.setText("    LEADERBOARD");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(166, 28, 97, 44);

        jLabel2.setText("Player1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(101, 78, 42, 29);

        jButton1.setText("BACK");
        getContentPane().add(jButton1);
        jButton1.setBounds(12, 11, 64, 24);

        jLabel4.setText("Player2");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(101, 114, 42, 26);

        jLabel5.setText("Player4");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(101, 182, 42, 26);

        jLabel6.setText("Player3");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(101, 148, 42, 27);

        jLabel7.setText("0000");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(272, 78, 34, 29);

        jLabel8.setText("0000");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(272, 113, 34, 28);

        jLabel9.setText("Player5");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(101, 215, 42, 28);

        jLabel10.setText("0000");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(272, 181, 34, 28);

        jLabel11.setText("0000");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(272, 215, 28, 28);

        jLabel12.setText("0000");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(272, 147, 34, 28);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
