/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu_interface;

/**
 *
 * @author BERKYILDIZ
 */
public class LeaderboardView extends javax.swing.JFrame {

    /**
     * Creates new form LeaderboardView
     */
    public LeaderboardView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("    LEADERBOARD");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 150, 120, 100);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Player1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 200, 70, 90);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 30, 59, 32);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Player2");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 230, 70, 80);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Player4");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 300, 70, 80);

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Player3");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 270, 70, 80);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("0000");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(450, 200, 60, 90);

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("0000");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(450, 230, 60, 80);

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Player5");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(280, 330, 70, 80);

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("0000");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(450, 300, 60, 80);

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("0000");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(450, 330, 50, 80);

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("0000");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(450, 270, 60, 80);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whitte.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 3, true));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(230, 150, 320, 320);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whitte.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 3, true));
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 20, 80, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp Image 2018-12-28 at 01.13.32.jpeg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
