/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu_interface;

import menu_management.MainMenuController;

/**
 *
 * @author BERKYILDIZ
 */
public class LevelScreen extends javax.swing.JPanel {
    MainMenuController menuController;
    /**
     * Creates new form LevelScreen
     */
    public LevelScreen(MainMenuController menuController) {
        this.menuController = menuController;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        level2Button = new javax.swing.JButton();
        level3Button = new javax.swing.JButton();
        Level4Button = new javax.swing.JButton();
        level5Button = new javax.swing.JButton();
        level6Button = new javax.swing.JButton();
        level7Button = new javax.swing.JButton();
        level8Button = new javax.swing.JButton();
        level1Button = new javax.swing.JButton();
        level9Button = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 102));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(null);

        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(11, 11, 100, 50);

        jLabel1.setText("           LEVELS");
        add(jLabel1);
        jLabel1.setBounds(350, 99, 100, 50);

        level2Button.setText("Level 2");
        level2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level2ButtonActionPerformed(evt);
            }
        });
        add(level2Button);
        level2Button.setBounds(300, 190, 200, 50);

        level3Button.setText("Level 3");
        level3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level3ButtonActionPerformed(evt);
            }
        });
        add(level3Button);
        level3Button.setBounds(550, 190, 200, 50);

        Level4Button.setText("Level 4");
        Level4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Level4ButtonActionPerformed(evt);
            }
        });
        add(Level4Button);
        Level4Button.setBounds(50, 310, 200, 50);

        level5Button.setText("Level 5");
        level5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level5ButtonActionPerformed(evt);
            }
        });
        add(level5Button);
        level5Button.setBounds(300, 310, 200, 50);

        level6Button.setText("Level 6");
        level6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level6ButtonActionPerformed(evt);
            }
        });
        add(level6Button);
        level6Button.setBounds(550, 310, 200, 50);

        level7Button.setText("Level 7");
        level7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level7ButtonActionPerformed(evt);
            }
        });
        add(level7Button);
        level7Button.setBounds(50, 430, 200, 50);

        level8Button.setText("Level 8");
        level8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level8ButtonActionPerformed(evt);
            }
        });
        add(level8Button);
        level8Button.setBounds(300, 430, 200, 50);

        level1Button.setText("Level 1");
        level1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level1ButtonActionPerformed(evt);
            }
        });
        add(level1Button);
        level1Button.setBounds(50, 190, 200, 50);

        level9Button.setText("Level 9");
        level9Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level9ButtonActionPerformed(evt);
            }
        });
        add(level9Button);
        level9Button.setBounds(550, 430, 200, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        menuController.setLevelNo(-1);
        menuController.showView("gamemode");
    }//GEN-LAST:event_backButtonActionPerformed

    private void level1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level1ButtonActionPerformed
        menuController.setLevelNo(1);
        menuController.initLevel();
    }//GEN-LAST:event_level1ButtonActionPerformed

    private void level2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level2ButtonActionPerformed
        menuController.setLevelNo(2);

    }//GEN-LAST:event_level2ButtonActionPerformed

    private void level3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level3ButtonActionPerformed
        menuController.setLevelNo(3);
    }//GEN-LAST:event_level3ButtonActionPerformed

    private void Level4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Level4ButtonActionPerformed
        menuController.setLevelNo(4);
    }//GEN-LAST:event_Level4ButtonActionPerformed

    private void level5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level5ButtonActionPerformed
        menuController.setLevelNo(5);
    }//GEN-LAST:event_level5ButtonActionPerformed

    private void level6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level6ButtonActionPerformed
        menuController.setLevelNo(6);
    }//GEN-LAST:event_level6ButtonActionPerformed

    private void level7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level7ButtonActionPerformed
        menuController.setLevelNo(7);
    }//GEN-LAST:event_level7ButtonActionPerformed

    private void level8ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level8ButtonActionPerformed
        menuController.setLevelNo(8);
    }//GEN-LAST:event_level8ButtonActionPerformed

    private void level9ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level9ButtonActionPerformed
        menuController.setLevelNo(9);
    }//GEN-LAST:event_level9ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Level4Button;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton level1Button;
    private javax.swing.JButton level2Button;
    private javax.swing.JButton level3Button;
    private javax.swing.JButton level5Button;
    private javax.swing.JButton level6Button;
    private javax.swing.JButton level7Button;
    private javax.swing.JButton level8Button;
    private javax.swing.JButton level9Button;
    // End of variables declaration//GEN-END:variables
}
