/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu_interface;

import menu_management.MainMenuController;

/**
 *
 * @author murattuver
 */
public class MultiMenu extends javax.swing.JPanel {

    public MainMenuController menuController;
    /**
     * Creates new form MultiMenu
     */
    public MultiMenu(MainMenuController menuController) {
        this.menuController = menuController;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signOutButton = new javax.swing.JButton();
        createLobbyButton = new javax.swing.JButton();
        joinButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(null);

        signOutButton.setText("SignOut");
        signOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutButtonActionPerformed(evt);
            }
        });
        add(signOutButton);
        signOutButton.setBounds(300, 350, 177, 49);

        createLobbyButton.setText("Create a Lobby");
        createLobbyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createLobbyButtonActionPerformed(evt);
            }
        });
        add(createLobbyButton);
        createLobbyButton.setBounds(300, 230, 177, 49);

        joinButton.setText("Join a Game");
        joinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinButtonActionPerformed(evt);
            }
        });
        add(joinButton);
        joinButton.setBounds(300, 290, 177, 49);

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("KATAMINO-ONLINE");
        add(jLabel1);
        jLabel1.setBounds(270, 110, 250, 48);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whitte.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 3, true));
        add(jLabel3);
        jLabel3.setBounds(200, 80, 380, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backG.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBounds(new java.awt.Rectangle(0, 0, 800, 600));
        add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void createLobbyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createLobbyButtonActionPerformed
        menuController.getSoundManager().playSound();
        menuController.showView("createlobby");
    }//GEN-LAST:event_createLobbyButtonActionPerformed

    private void joinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinButtonActionPerformed
        menuController.getSoundManager().playSound();
        menuController.showView("joinlobby");
    }//GEN-LAST:event_joinButtonActionPerformed

    private void signOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutButtonActionPerformed
        menuController.getSoundManager().playSound();
        menuController.showView("numberofplayer");
    }//GEN-LAST:event_signOutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createLobbyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton joinButton;
    private javax.swing.JButton signOutButton;
    // End of variables declaration//GEN-END:variables
}
