/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu_interface;

import menu_management.MainMenuController;

/**
 *
 * @author BERKYILDIZ
 */
public class NumberOfPlayerView extends javax.swing.JPanel {
    
    MainMenuController menuManager;

    /**
     * Creates new form NumberOfPlayerView
     */
    public NumberOfPlayerView(MainMenuController menuManager) {
        this.menuManager = menuManager;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        backButton = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        multiPlayerButton = new javax.swing.JButton();
        singlePlayerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(null);

        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(11, 11, 100, 50);

        title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText("SELECT PLAYER");
        add(title);
        title.setBounds(300, 70, 210, 50);

        multiPlayerButton.setText("Multiplayer");
        multiPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiPlayerButtonActionPerformed(evt);
            }
        });
        add(multiPlayerButton);
        multiPlayerButton.setBounds(300, 376, 200, 100);

        singlePlayerButton.setText("Single Player");
        singlePlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singlePlayerButtonActionPerformed(evt);
            }
        });
        add(singlePlayerButton);
        singlePlayerButton.setBounds(300, 206, 200, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whitte.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 3, true));
        jLabel1.setLocation(new java.awt.Point(190, 40));
        jLabel1.setSize(new java.awt.Dimension(410, 100));
        add(jLabel1);
        jLabel1.setBounds(220, 40, 380, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backG.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 849, 600);
    }// </editor-fold>                        

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {  
        menuManager.getSoundManager().playSound();
        menuManager.setNumberOfPlayers(0);
        menuManager.showView("mainmenu");
    }                                          

    private void singlePlayerButtonActionPerformed(java.awt.event.ActionEvent evt) { 
        menuManager.getSoundManager().playSound();
        menuManager.setNumberOfPlayers(1);
        menuManager.showView("gamemode");
    }                                                  

    private void multiPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) { 
        menuManager.getSoundManager().playSound();
        menuManager.setNumberOfPlayers(2);
        menuManager.showView("login");
        menuManager.initNetwork();
        //menuManager.initLevel();
    }                                                 


    // Variables declaration - do not modify                     
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton multiPlayerButton;
    private javax.swing.JButton singlePlayerButton;
    private javax.swing.JLabel title;
    // End of variables declaration                   
}