/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu_interface;

import game_management.SoundManager;
import menu_management.MainMenuController;
import java.util.LinkedList;
import java.util.Properties;

/**
 *
 * @author Cerca-Trova
 */
public class OptionsView extends javax.swing.JPanel {
    
    //IMPORTANT NOTE: Change this if you add a resolution.
    
    //Reference to the Controller.
    MainMenuController menuController = null;
    SoundManager soundManager;
   
    /**
     * Creates new form OptionsView
     */
    public OptionsView(MainMenuController gameController) {
        
        //Connecting view to the Controller.
        this.menuController = gameController;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soundGroup = new javax.swing.ButtonGroup();
        musicGroup = new javax.swing.ButtonGroup();
        themeGroup = new javax.swing.ButtonGroup();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        musicOn = new javax.swing.JRadioButton();
        musicOff = new javax.swing.JRadioButton();
        soundOn = new javax.swing.JRadioButton();
        soundOff = new javax.swing.JRadioButton();
        archTheme = new javax.swing.JRadioButton();
        manTheme = new javax.swing.JRadioButton();
        meTheme = new javax.swing.JRadioButton();
        csTheme = new javax.swing.JRadioButton();

        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("                          OPTIONS");

        jLabel2.setText("                           Sound");

        jLabel3.setText("                           Music");

        jLabel4.setText("                           Theme");

        musicGroup.add(musicOn);
        musicOn.setSelected(true);
        musicOn.setText("ON");
        musicOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicOnActionPerformed(evt);
            }
        });

        musicGroup.add(musicOff);
        musicOff.setText("OFF");
        musicOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicOffActionPerformed(evt);
            }
        });

        soundGroup.add(soundOn);
        soundOn.setSelected(true);
        soundOn.setText("ON");
        soundOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundOnActionPerformed(evt);
            }
        });

        soundGroup.add(soundOff);
        soundOff.setText("OFF");
        soundOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundOffActionPerformed(evt);
            }
        });

        themeGroup.add(archTheme);
        archTheme.setText("ARCH");
        archTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archThemeActionPerformed(evt);
            }
        });

        themeGroup.add(manTheme);
        manTheme.setText("MAN");

        themeGroup.add(meTheme);
        meTheme.setText("ME");
        meTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meThemeActionPerformed(evt);
            }
        });

        themeGroup.add(csTheme);
        csTheme.setText("CS");
        csTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csThemeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(musicOn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(musicOff))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(soundOn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(soundOff)))
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(273, 273, 273))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(archTheme)
                        .addGap(12, 12, 12)
                        .addComponent(csTheme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(manTheme)
                        .addGap(12, 12, 12)
                        .addComponent(meTheme)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soundOn)
                    .addComponent(soundOff))
                .addGap(36, 36, 36)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musicOn)
                    .addComponent(musicOff))
                .addGap(36, 36, 36)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(archTheme)
                    .addComponent(manTheme)
                    .addComponent(meTheme)
                    .addComponent(csTheme))
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        menuController.showView("mainmenu");
    }//GEN-LAST:event_backButtonActionPerformed

    private void musicOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicOnActionPerformed
        menuController.getSoundManager().resume();
    }//GEN-LAST:event_musicOnActionPerformed

    private void musicOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicOffActionPerformed
        menuController.getSoundManager().pause();
    }//GEN-LAST:event_musicOffActionPerformed

    private void soundOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundOnActionPerformed
        menuController.getSoundManager().playSound();
    }//GEN-LAST:event_soundOnActionPerformed

    private void soundOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundOffActionPerformed
        menuController.getSoundManager().stopSound();
    }//GEN-LAST:event_soundOffActionPerformed

    private void archThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archThemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_archThemeActionPerformed

    private void csThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csThemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csThemeActionPerformed

    private void meThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meThemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meThemeActionPerformed
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton archTheme;
    private javax.swing.JButton backButton;
    private javax.swing.JRadioButton csTheme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton manTheme;
    private javax.swing.JRadioButton meTheme;
    private javax.swing.ButtonGroup musicGroup;
    private javax.swing.JRadioButton musicOff;
    private javax.swing.JRadioButton musicOn;
    private javax.swing.ButtonGroup soundGroup;
    private javax.swing.JRadioButton soundOff;
    private javax.swing.JRadioButton soundOn;
    private javax.swing.ButtonGroup themeGroup;
    // End of variables declaration//GEN-END:variables
}
