/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu_interface;

import game_management.SoundManager;
import menu_management.MainMenuController;

/**
 *
 * @author Cerca-Trova
 */
public class OptionsView extends javax.swing.JPanel {
    
    //IMPORTANT NOTE: Change this if you add a resolution.
    
    //Reference to the Controller.
    MainMenuController menuController = null;
    SoundManager soundManager;
   
    /**
     * Creates new form OptionsView
     */
    public OptionsView(MainMenuController gameController) {
        
        //Connecting view to the Controller.
        this.menuController = gameController;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        soundGroup = new javax.swing.ButtonGroup();
        musicGroup = new javax.swing.ButtonGroup();
        themeGroup = new javax.swing.ButtonGroup();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        musicOn = new javax.swing.JRadioButton();
        musicOff = new javax.swing.JRadioButton();
        soundOn = new javax.swing.JRadioButton();
        soundOff = new javax.swing.JRadioButton();
        archTheme = new javax.swing.JRadioButton();
        manTheme = new javax.swing.JRadioButton();
        meTheme = new javax.swing.JRadioButton();
        csTheme = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(0, 204, 255));
        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        setLayout(null);

        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(11, 11, 100, 50);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("OPTIONS");
        jLabel1.setLocation(new java.awt.Point(310, 70));
        add(jLabel1);
        jLabel1.setBounds(330, 70, 180, 50);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("                           Sound");
        add(jLabel2);
        jLabel2.setBounds(220, 160, 240, 50);



        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("                           Music");
        add(jLabel3);
        jLabel3.setBounds(220, 250, 290, 50);

        soundGroup.add(soundOn);
        soundOn.setSelected(true);
        soundOn.setText("ON");
        soundOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundOnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("                           Theme");
        add(jLabel4);
        jLabel4.setBounds(210, 370, 250, 50);
        soundGroup.add(soundOff);
        soundOff.setText("OFF");
        soundOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundOffActionPerformed(evt);
            }
        });

        themeGroup.add(archTheme);
        archTheme.setText("ARCH");
        archTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archThemeActionPerformed(evt);
            }
        });

        themeGroup.add(manTheme);
        manTheme.setText("MAN");
        manTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manThemeActionPerformed(evt);
            }
        });


        themeGroup.add(meTheme);
        meTheme.setText("ME");
        meTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meThemeActionPerformed(evt);
            }
        });


        themeGroup.add(csTheme);
        csTheme.setText("CS");
        csTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csThemeActionPerformed(evt);
            }
        });


        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whitte.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 3, true));
        jLabel6.setLocation(new java.awt.Point(190, 40));
        jLabel6.setSize(new java.awt.Dimension(410, 100));
        add(jLabel6);
        jLabel6.setBounds(230, 50, 350, 90);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whitte.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 3, true));
        add(jLabel7);
        jLabel7.setBounds(235, 156, 340, 370);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backG.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        add(jLabel5);
        jLabel5.setBounds(0, 0, 810, 600);
    }// </editor-fold>                        

    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {                                

    }                               

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        menuController.getSoundManager().playSound();
        menuController.showView("mainmenu");
    }                                          

    private void musicOnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        menuController.getSoundManager().playSound();
        menuController.getSoundManager().resume();
    }                                       

    private void musicOffActionPerformed(java.awt.event.ActionEvent evt) {                                         
        menuController.getSoundManager().playSound();
        menuController.getSoundManager().pause();
    }                                        

    private void soundOnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        menuController.getSoundManager().setClosed(false);
        menuController.getSoundManager().playSound();
    }                                       

    private void soundOffActionPerformed(java.awt.event.ActionEvent evt) {                                         
        menuController.getSoundManager().stopSound();
        menuController.getSoundManager().setClosed(true);
    }                                        

    private void archThemeActionPerformed(java.awt.event.ActionEvent evt) {                                          
        menuController.getSoundManager().playSound();
    }                                         

    private void csThemeActionPerformed(java.awt.event.ActionEvent evt) {                                        
        menuController.getSoundManager().playSound();
    }                                       

    private void meThemeActionPerformed(java.awt.event.ActionEvent evt) {                                        
        menuController.getSoundManager().playSound();
    }                                       

    private void manThemeActionPerformed(java.awt.event.ActionEvent evt) {                                         
        menuController.getSoundManager().playSound();
    }                                        
    
   

    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton archTheme;
    private javax.swing.JButton backButton;
    private javax.swing.JRadioButton csTheme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton manTheme;
    private javax.swing.JRadioButton meTheme;
    private javax.swing.ButtonGroup musicGroup;
    private javax.swing.JRadioButton musicOff;
    private javax.swing.JRadioButton musicOn;
    private javax.swing.ButtonGroup soundGroup;
    private javax.swing.JRadioButton soundOff;
    private javax.swing.JRadioButton soundOn;
    private javax.swing.ButtonGroup themeGroup;
    // End of variables declaration                   
}
