/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu_interface;

import menu_management.MainMenuController;

/**
 *
 * @author murattuver
 */
public class SignUpScreen extends javax.swing.JPanel {

    MainMenuController menuController;
    /**
     * Creates new form SignUpScreen
     */
    public SignUpScreen(MainMenuController menuController) {
        this.menuController = menuController;
        initComponents();
        notMatchedField.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordField1 = new javax.swing.JPasswordField();
        passwordField2 = new javax.swing.JPasswordField();
        mailAdressField = new javax.swing.JFormattedTextField();
        signupButton = new javax.swing.JButton();
        notMatchedField = new javax.swing.JTextField();
        nickNameField = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 153, 255));
        setLayout(null);

        passwordField1.setText("jPasswordField1");
        passwordField1.setMaximumSize(new java.awt.Dimension(134, 22));
        passwordField1.setMinimumSize(new java.awt.Dimension(134, 22));
        passwordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordField1FocusGained(evt);
            }
        });
        add(passwordField1);
        passwordField1.setBounds(333, 131, 155, 22);

        passwordField2.setText("jPasswordField2");
        passwordField2.setMaximumSize(new java.awt.Dimension(134, 22));
        passwordField2.setMinimumSize(new java.awt.Dimension(134, 22));
        passwordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordField2FocusGained(evt);
            }
        });
        add(passwordField2);
        passwordField2.setBounds(333, 191, 155, 22);

        mailAdressField.setText("example@mail.com");
        mailAdressField.setMaximumSize(new java.awt.Dimension(72, 26));
        mailAdressField.setMinimumSize(new java.awt.Dimension(72, 26));
        mailAdressField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailAdressFieldFocusGained(evt);
            }
        });
        mailAdressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailAdressFieldActionPerformed(evt);
            }
        });
        add(mailAdressField);
        mailAdressField.setBounds(333, 95, 155, 26);

        signupButton.setText("Sign Up");
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });
        add(signupButton);
        signupButton.setBounds(333, 281, 78, 32);

        notMatchedField.setEditable(false);
        notMatchedField.setText("Passwords do not match.");
        notMatchedField.setFocusable(false);
        notMatchedField.setOpaque(false);
        notMatchedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notMatchedFieldActionPerformed(evt);
            }
        });
        add(notMatchedField);
        notMatchedField.setBounds(231, 316, 317, 24);

        nickNameField.setText("NickName");
        add(nickNameField);
        nickNameField.setBounds(333, 237, 155, 24);

        jTextField5.setText("At least 6 characters long.");
        add(jTextField5);
        jTextField5.setBounds(333, 155, 179, 24);

        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(11, 11, 100, 50);

        jFormattedTextField1.setEditable(false);
        jFormattedTextField1.setText("Password:");
        add(jFormattedTextField1);
        jFormattedTextField1.setBounds(207, 131, 120, 26);

        jFormattedTextField2.setEditable(false);
        jFormattedTextField2.setText("Email Address:");
        add(jFormattedTextField2);
        jFormattedTextField2.setBounds(207, 95, 120, 26);

        jFormattedTextField3.setEditable(false);
        jFormattedTextField3.setText("re-Password:");
        add(jFormattedTextField3);
        jFormattedTextField3.setBounds(207, 191, 120, 26);

        jFormattedTextField4.setEditable(false);
        jFormattedTextField4.setText("NickName:");
        add(jFormattedTextField4);
        jFormattedTextField4.setBounds(207, 237, 120, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backG.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setSize(new java.awt.Dimension(800, 600));
        add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void mailAdressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailAdressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailAdressFieldActionPerformed

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        menuController.getSoundManager().playSound();
        String username = mailAdressField.getText();
        String p1 = new String( passwordField1.getPassword());
        String p2 = new String( passwordField2.getPassword());
        String nick = nickNameField.getText();
        boolean isSucceed = false;
        if(!p1.equals(p2)){
            notMatchedField.setText("Password does not match.");
            notMatchedField.setVisible(true);
            this.repaint();
            this.validate();
            
        }else if(p1.length() < 6){
            notMatchedField.setText("Password needs to be at least 6 characters long.");
            notMatchedField.setVisible(true);
            this.repaint();
            this.validate();
        } else{
            isSucceed = menuController.createUser(username, p1, nick);
        }
        
        if(isSucceed){
            notMatchedField.setText("Signed Up Successfully.");
            notMatchedField.setVisible(true);
            this.repaint();
            this.validate();
        }

    }//GEN-LAST:event_signupButtonActionPerformed

    private void notMatchedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notMatchedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notMatchedFieldActionPerformed

    private void passwordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordField1FocusGained
        passwordField1.setText("");
    }//GEN-LAST:event_passwordField1FocusGained

    private void passwordField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordField2FocusGained
        passwordField2.setText("");

    }//GEN-LAST:event_passwordField2FocusGained

    private void mailAdressFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailAdressFieldFocusGained
        mailAdressField.setText("");

    }//GEN-LAST:event_mailAdressFieldFocusGained

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        menuController.getSoundManager().playSound();  
        menuController.showView("login");
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JFormattedTextField mailAdressField;
    private javax.swing.JTextField nickNameField;
    private javax.swing.JTextField notMatchedField;
    private javax.swing.JPasswordField passwordField1;
    private javax.swing.JPasswordField passwordField2;
    private javax.swing.JButton signupButton;
    // End of variables declaration//GEN-END:variables
}
